/**
   @file   ApplyEnergyResponse.hpp
   @date   2020/08/24
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef ApplyEnergyResponse_hpp
#define ApplyEnergyResponse_hpp

#include <VANL_Module.hpp>

class ApplyEnergyResponse : public anl::VANL_Module
{
public:
    ApplyEnergyResponse();
    ~ApplyEnergyResponse();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;

private:
    
    double randomize_energy_cathode
    (double energy, double electronics_noise, const std::string& mate);
    double randomize_energy_anode
    (double energy, double electronics_noise, const std::string& mate);
    double energy_resolution_cathode
    (double energy, double electronics_noise, const std::string& mate);
    double energy_resolution_anode
    (double energy, double electronics_noise, const std::string& mate);
    
};

#endif

