/**
   @file   BeginG4TreeAnalysis.hpp
   @date   2020/08/24
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef BeginG4TreeAnalysis_hpp
#define BeginG4TreeAnalysis_hpp

#include <VANL_Module.hpp>

class BeginG4TreeAnalysis : public anl::VANL_Module
{
public:
    BeginG4TreeAnalysis();
    ~BeginG4TreeAnalysis();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
};

#endif

