/**
   @file   ConvertToLv1Data.hpp
   @date   2020/09/03
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef ConvertToLv1Data_hpp
#define ConvertToLv1Data_hpp

#include <VANL_Module.hpp>

class ConvertToLv1Data : public anl::VANL_Module
{
public:
    ConvertToLv1Data();
    ~ConvertToLv1Data();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
};

#endif

