/**
   @file   CoupleHit.hpp
   @date   2020/08/24
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef CoupleHit_hpp
#define CoupleHit_hpp

#include <VANL_Module.hpp>

class CoupleHit : public anl::VANL_Module
{
public:
    CoupleHit();
    ~CoupleHit();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
};

#endif

