/**
   @file   CutAnalysisThreshold.hpp
   @date   2020/08/24
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef CutAnalysisThreshold_hpp
#define CutAnalysisThreshold_hpp

#include <VANL_Module.hpp>

class CutAnalysisThreshold : public anl::VANL_Module
{
public:
    CutAnalysisThreshold();
    ~CutAnalysisThreshold();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
};

#endif

