/**
   @file   MergeAdjacentStrip.hpp
   @date   2020/08/24
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef MergeAdjacentStrip_hpp
#define MergeAdjacentStrip_hpp

#include <VANL_Module.hpp>

class MergeAdjacentStrip : public anl::VANL_Module
{
public:
    MergeAdjacentStrip();
    ~MergeAdjacentStrip();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
};

#endif

