/**
   @file   SelectHitPattern.hpp
   @date   2020/08/24
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef SelectHitPattern_hpp
#define SelectHitPattern_hpp

#include <VANL_Module.hpp>

class SelectHitPattern : public anl::VANL_Module
{
public:
    SelectHitPattern();
    ~SelectHitPattern();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
};

#endif

