/**
   @file   ConvertGhittree.hpp
   @date   2020/05/20
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef ConvertGhittree_hpp
#define ConvertGhittree_hpp

#include <VANL_Module.hpp>
#include "ProjectCone3D.hpp"

class ConvertGhittree : public anl::VANL_Module
{
    
public:
    
    ConvertGhittree();
    ~ConvertGhittree();

    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;

private:

    ProjectCone3D * event_extractor;
    TFile * outfile;

    TFile* open_file(std::string file_name);
    
};

#endif

