/**
   @file   Iterate2Photon3D.hpp
   @date   2020/05/18
   @author 
   @detail Automatically generated by make_anlpy_project.sh 1.0.0
**/

#ifndef Iterate2Photon3D_hpp
#define Iterate2Photon3D_hpp

#include <VANL_Module.hpp>
#include "IterateCone3D.hpp"

#include <TFile.h>
#include <TTree.h>
class TH3F;

class Iterate2Photon3D : public anl::VANL_Module
{

public:
    
    Iterate2Photon3D();
    ~Iterate2Photon3D();
    
    int mod_bgnrun() override;
    int mod_ana() override;
    int mod_endrun() override;
    
protected:
    
    TFile * open_tfile(const std::string& key_of_file);
    TTree * get_ttree
    (const std::string& key_of_file, const std::string& key_of_tree);
    TFile * recreate_tfile(const std::string& key_of_file);

private:
    IterateCone3D::resptree_event event1;
    IterateCone3D::resptree_event event2;

    TFile * output_file;
    TH3F * sbp_image;

    //int number_of_events;
    int eventid;
    int current_entry;
};

#endif

